module.exports = {
    "port": 6052,
    "apiEndpoint": "http://amcqaemr01.ach.jo",
    "apiEndpointPort": "8000",
    "apiSAPEndpoint": "/sap/opu/odata4/sap/znfhir/default/sap/",
    "apiSAPCatlogEndpoint": "/sap/opu/odata/sap/",
    "apiCatalogEndpoint": "ZNFHIR_EKRDX_VITALSETT_SRV/VitalCatSettSet",
    "apiVitalEndpoint": "znfhir_patvitcat_service/0001",
    "apiVitalValueEndpoint": "znfhir_patvitvalue_service/001",
    "apiPatientEndpoint": "znfhir_encounter_service/0001",
    "apiPatientUserEndpoint": "ZN_E_KARDEX_SRV",
    "apiZGENERICSRV": "ZNHCGENERIC_SRV",
    "apiZNISHPATCASEDATA": "ZNISH_PATCASEDATA_SRV",
    "apiZNPMDDOCUMENTSRV": "ZN_PMD_DOCUMENT_SRV",
    "apiZNNURSINGASSESMENTSSRV": "ZN_NURSING_ASSESMENTS_SRV",
    "apiZNPATIENTDOCUMENTSRV": "ZN_PATIENT_DOCUMENT_SRV",
    "apiZABEMRPHYORDERSRV": "ZAB_EMR_PHY_ORDER_SRV",
    "apiZABEMRPDCNOTESSRV": "ZAB_EMR_PDC_NOTES_SRV",
    "apiZABEMRORDSETSRV": "ZAB_EMR_ORDSET_SRV",
    "apiZNNEWBORN": "ZN_NEWBORN_PHY_ASSES_SRV",
    "apiZNURINARYCATHETERSRV": "ZN_URINARY_CATHETER_SRV",
    "apiZNCVCMAINTENANCE": "ZN_CVC_MAINTENANCE_SRV",
    "apiZNNURSERESTRAINTSRV": "ZN_NURSE_RESTRAINT_SRV",
    "apiZNCCPOTSRV": "ZN_CCPOT_SRV",
    "apiZNNICUADMSERV":"ZN_NICU_ADM_SRV",
    "apiZNEMERGENCYDASHBOARDSRV": "ZN_EMERGENCY_DASHBOARD_SRV",
    "apiZABEMRDAYCARESRV":"ZAB_EMR_DAYCARE_SRV",
    "apiZABEMGYWRKLISTSRV": "ZAB_EMGY_WRKLIST_SRV",
    "apiZNNURSINGACTIONEMARSRV": "ZN_NURSING_ACTION_EMAR_SRV",
    "apiZABEMRDIAGNOSISSRV": "ZAB_EMR_DIAGNOSIS_SRV",
    "apiZNISHMEDDOCATTACHMENTSRV": "ZNISHMED_DOC_ATTACHMENT_SRV",
    "apiZABEMRIPLISTSRV": "ZAB_EMR_IP_LIST_SRV",
    "apiZABEMRMDSRV": "ZAB_EMR_MD_SRV",
    "apiZNVITALSIGNSSRV": "ZN_VITAL_SIGNS_SRV",
    "apiZNUPDATECASESTATUSSRV":"ZN_UPDATE_CASE_STATUS_SRV",
    "apiZNERPHYSDOCSRV":"ZN_ER_PHYS_DOC_SRV",
    "apiZABEMRIPNDOCSRV":"ZAB_EMR_IP_NDOC_SRV",
    "apiZNEDUASSESSRV":"ZN_EDU_ASSES_SRV",
    "apiZABEMRDIALYSISSRV":"ZAB_EMR_DIALYSIS_SRV",
    "apiZNPOINTSALESRV":"ZN_POINT_SALE_SRV",
    "apiZNDOCATTACHSRV":"ZN_DOC_ATTACH_SRV",
    "apiZABEMRDOCTEMPLATESRV":"ZAB_EMR_DOC_TEMPLATE_SRV",
    "apiZABEMRPNOTESRV":"ZAB_EMR_PNOTE_SRV",
    "apiZABEMRCORDSRV":"ZAB_EMR_CORD_SRV",
    "apiZABEMRPATORGSRV":"ZAB_EMR_PATORG_SRV",
    "apiZNSOAPSRV":"ZN_SOAP_SRV",
    "apiZNOBPPTSRV":"ZN_OBPPT_SRV",
    "apiZNOBANTSRV":"ZN_OBANT_SRV",
    "apiZEMERGENCYANALYSISSRV":"ZEMERGENCY_ANALYSIS_SRV",
    "apiZNOBGYPHYSSRV":"ZN_OBGYPHYS_SRV",
    "apiZNNEOPNOTESRV":"ZN_NEOPNOTE_SRV",
    "apiZNNOENATMEDREPSRV":"ZN_NOENAT_MEDREP_SRV",
    "apiZNROOMASSIGNSRV":"ZN_ROOM_ASSIGN_SRV",
    "apiZNPHYSICIANASSESSRV":"ZN_PHYSICIAN_ASSES_SRV",
    "apiZABUSERMGMTSRV": "ZAB_USER_MGMT_SRV",
    "apiZNFAMILYHISTSRV": "ZN_FAMILY_HIST_SRV",
    "apiZABEMRVISITNOTESRV": "ZAB_EMR_VISITNOTE_SRV",
    "apiZNTRANSFERASSESSRV":"ZN_TRANSFER_ASSES_SRV",
    "apiZNPATMATCONSUMSRV":"ZN_PATMATCONSUM_SRV",
    "ZNISHMEDORDER_HIST_SRV":"ZNISHMEDORDER_HIST_SRV",
    "apiZNISHMEDEORDERSRV":"ZNISHMEDEORDER_SRV",
    "apiZNDAILYSISASSESSRV":"ZN_DAILYSIS_ASSES_SRV",
    "apiZNMORSEFALLSCALESRV":"ZN_MORSE_FALL_SCALE_SRV",
    "apiZNHEMOCATHETERSRV": "ZN_HEMO_CATHETER_SRV",
    "apiZNNURSINGCARESRV": "ZN_NURSING_CARE_SRV",
    "apiZNNURSEDISCHSUMSRV": "ZN_NURSE_DISCH_SUM_SRV",
    "apiEndpointEMR": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNEEMR_SRV",
    "apiEndpointEMRInPatient": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/",
    "apiEndpointWidget": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZWIDGET_SRV",
    "apiEndpointIntegrationOrder": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNISHMEDEORDER_SRV",
    "apiEndpointIntegrationEPresc": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNISHMEDIC_EPRESCR_SRV",
    "apiEndpointIntegrationPatCase": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNISH_PATCASEDATA_SRV",
    "apiEndpointIntegrationEPrescriptionOrder": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNISHMEDEMAR_SRV",
    "apiEndpointIntegrationAdministration": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNISHMEDPLANNED_ADMIN_SRV",
    "apiEndpointIntegrationOrderdetails": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNISHMEDORDER_HIST_SRV/",
    "apiEndpointIntegrationsurgery": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZAB_EMR_SURGERY_SRV",
    "apiEndpointIntegrationAdminister": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_NURSING_ACTION_EMAR_SRV",
    "apiEndpointIntegrationVital": "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_VITAL_SIGNS_SRV",
    "apiEndpointIntegrationChemotherapy":"http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_CHEMO_MODULE_SRV",
    "apiEndpointIntegrationPatScalesSet":"http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_TRANSFER_ASSES_SRV",
    "apiEndpointIntegrationPriorToAdmission":"http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_PRIOR_ADMISSION_SRV",
    "apiEndpointIntegrationAppointments":"http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZAB_EMR_NAPP_SRV",
    "apiEndpointIntegrationClinicConfig":"http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_NURSE_CLIC_CONFIG_SRV",
    "apiEndpointIntegrationExceptCheckedOut":"http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_OP_LIST_SRV",
    "apiDischargeSummarySet": "ZAB_EMR_PDS_SRV",
    "apiZNMEDREPORTSRV":"ZN_MED_REPORT_SRV",    
    "apiZABEMRCONSULTORDSRV": "ZAB_EMR_CONSULT_ORD_SRV",
    "apiZABEMRNURSESRV":"ZAB_EMR_NURSE_SRV",
    "apiZABEMRNURSESRVPH":"ZAB_EMR_PHY_ORDER_SRV",
    "apiZNSCALESSRV":"ZN_SCALES_SRV",
    "apiZNERNURSINGSRV":"ZN_ER_NURSING_SRV",
    "apiZNSOCIALHABITSSRV":"ZN_SOCIAL_HABITS_SRV",
    "apiZNERELAPSEDTIMESRV":"ZN_ER_ELAPSED_TIME_SRV",
    "apiZNCARTRECEIVESRV":"ZN_CART_RECEIVE_SRV",
    "apiZNNURSEENDORSSRV":"ZN_NURSE_ENDORS_SRV",
    "apiZNSURGICALPASSPORTSRV":"ZN_SURGICAL_PASSPORT_SRV",
    "apiZNPAINASSESSRV":"ZN_PAIN_ASSES_SRV",
    "apiFISTULAGRAFTSRV":"ZN_FISTULA_GRAFT_SRV",
    "apiZNPATIENTSEARCHSRV": "ZN_PATIENT_SEARCH_SRV",
    "apiZNRESERVATION":"ZN_RESERVATION_SRV",
    "apiZNNURSINGADMASSSRV":"ZN_NURSING_ADM_ASS_SRV",
    "apiZNDIETSRV":"ZN_DIET_SRV",
    "apiZNINOUTSRV":"ZN_INOUT_SRV",
    "apiZNNURSINGASSESSV2SRV":"ZN_NURSING_ASSESS_V2_SRV",
    "apiZNPRECARDIACCATHSRV":"ZN_PRE_CARDIAC_CATH_SRV",
    "apiZNCPRSRV":"ZN_CPR_SRV",
    "apiZNCORRESPONDENCESRV":"ZN_CORRESPONDENCE_SRV",
    "apiZNMODIFIEDALDRETSRV":"ZN_MODIFIED_ALDRET_SRV",
    "apiZNTIMEOUTCHECKSRV":"ZN_TIME_OUT_CHECK_SRV",
    "apiZNNEONATALDISCHSRV":"ZN_NEONATAL_DISCH_SRV",
    "apiZNCVCINSERTIONSRV":"ZN_CVC_INSERTION_SRV",

    "apiDomain": "ach.jo",
    "AllowOriginDomain": "http://localhost:4200",
    "environment": "qa",
    "client": "210",
    "isLocalHost": true
};

//"apiEndpoint": "http://achdevemr01.ach.jo",
//"client":"100",